//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class InitSyncResponse : Message
    {
        public const string k_RosMessageName = "ril_msg/InitSync";
        public override string RosMessageName => k_RosMessageName;

        public long init_state;

        public InitSyncResponse()
        {
            this.init_state = 0;
        }

        public InitSyncResponse(long init_state)
        {
            this.init_state = init_state;
        }

        public static InitSyncResponse Deserialize(MessageDeserializer deserializer) => new InitSyncResponse(deserializer);

        private InitSyncResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.init_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.init_state);
        }

        public override string ToString()
        {
            return "InitSyncResponse: " +
            "\ninit_state: " + init_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
