//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class InitSyncRequest : Message
    {
        public const string k_RosMessageName = "ril_msg/InitSync";
        public override string RosMessageName => k_RosMessageName;

        public string[] activated_object;
        public Geometry.PointMsg[] position;
        public Geometry.QuaternionMsg[] orientation;
        public float[] joint_state;

        public InitSyncRequest()
        {
            this.activated_object = new string[0];
            this.position = new Geometry.PointMsg[0];
            this.orientation = new Geometry.QuaternionMsg[0];
            this.joint_state = new float[0];
        }

        public InitSyncRequest(string[] activated_object, Geometry.PointMsg[] position, Geometry.QuaternionMsg[] orientation, float[] joint_state)
        {
            this.activated_object = activated_object;
            this.position = position;
            this.orientation = orientation;
            this.joint_state = joint_state;
        }

        public static InitSyncRequest Deserialize(MessageDeserializer deserializer) => new InitSyncRequest(deserializer);

        private InitSyncRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activated_object, deserializer.ReadLength());
            deserializer.Read(out this.position, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.orientation, Geometry.QuaternionMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.joint_state, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.activated_object);
            serializer.Write(this.activated_object);
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.WriteLength(this.orientation);
            serializer.Write(this.orientation);
            serializer.WriteLength(this.joint_state);
            serializer.Write(this.joint_state);
        }

        public override string ToString()
        {
            return "InitSyncRequest: " +
            "\nactivated_object: " + System.String.Join(", ", activated_object.ToList()) +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\norientation: " + System.String.Join(", ", orientation.ToList()) +
            "\njoint_state: " + System.String.Join(", ", joint_state.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
