//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class MultiObjectPoseServiceResponse : Message
    {
        public const string k_RosMessageName = "ril_msg/MultiObjectPoseService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg[] object_pose;
        public string[] object_name;

        public MultiObjectPoseServiceResponse()
        {
            this.object_pose = new Geometry.PoseMsg[0];
            this.object_name = new string[0];
        }

        public MultiObjectPoseServiceResponse(Geometry.PoseMsg[] object_pose, string[] object_name)
        {
            this.object_pose = object_pose;
            this.object_name = object_name;
        }

        public static MultiObjectPoseServiceResponse Deserialize(MessageDeserializer deserializer) => new MultiObjectPoseServiceResponse(deserializer);

        private MultiObjectPoseServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_pose, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.object_name, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.object_pose);
            serializer.Write(this.object_pose);
            serializer.WriteLength(this.object_name);
            serializer.Write(this.object_name);
        }

        public override string ToString()
        {
            return "MultiObjectPoseServiceResponse: " +
            "\nobject_pose: " + System.String.Join(", ", object_pose.ToList()) +
            "\nobject_name: " + System.String.Join(", ", object_name.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
