//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class MultiObjectPoseServiceRequest : Message
    {
        public const string k_RosMessageName = "ril_msg/MultiObjectPoseService";
        public override string RosMessageName => k_RosMessageName;

        public string[] object_name;

        public MultiObjectPoseServiceRequest()
        {
            this.object_name = new string[0];
        }

        public MultiObjectPoseServiceRequest(string[] object_name)
        {
            this.object_name = object_name;
        }

        public static MultiObjectPoseServiceRequest Deserialize(MessageDeserializer deserializer) => new MultiObjectPoseServiceRequest(deserializer);

        private MultiObjectPoseServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_name, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.object_name);
            serializer.Write(this.object_name);
        }

        public override string ToString()
        {
            return "MultiObjectPoseServiceRequest: " +
            "\nobject_name: " + System.String.Join(", ", object_name.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
