//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class ObjectPoseServiceResponse : Message
    {
        public const string k_RosMessageName = "ril_msg/ObjectPoseService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg object_pose;
        public Geometry.Vector3Msg object_size;

        public ObjectPoseServiceResponse()
        {
            this.object_pose = new Geometry.PoseMsg();
            this.object_size = new Geometry.Vector3Msg();
        }

        public ObjectPoseServiceResponse(Geometry.PoseMsg object_pose, Geometry.Vector3Msg object_size)
        {
            this.object_pose = object_pose;
            this.object_size = object_size;
        }

        public static ObjectPoseServiceResponse Deserialize(MessageDeserializer deserializer) => new ObjectPoseServiceResponse(deserializer);

        private ObjectPoseServiceResponse(MessageDeserializer deserializer)
        {
            this.object_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.object_size = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_pose);
            serializer.Write(this.object_size);
        }

        public override string ToString()
        {
            return "ObjectPoseServiceResponse: " +
            "\nobject_pose: " + object_pose.ToString() +
            "\nobject_size: " + object_size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
