//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class ObjectPoseResponse : Message
    {
        public const string k_RosMessageName = "ril_msg/ObjectPose";
        public override string RosMessageName => k_RosMessageName;

        public long init_state;

        public ObjectPoseResponse()
        {
            this.init_state = 0;
        }

        public ObjectPoseResponse(long init_state)
        {
            this.init_state = init_state;
        }

        public static ObjectPoseResponse Deserialize(MessageDeserializer deserializer) => new ObjectPoseResponse(deserializer);

        private ObjectPoseResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.init_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.init_state);
        }

        public override string ToString()
        {
            return "ObjectPoseResponse: " +
            "\ninit_state: " + init_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
