//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class ObjectPoseRequest : Message
    {
        public const string k_RosMessageName = "ril_msg/ObjectPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg[] position;
        public Geometry.QuaternionMsg[] orientation;

        public ObjectPoseRequest()
        {
            this.position = new Geometry.PointMsg[0];
            this.orientation = new Geometry.QuaternionMsg[0];
        }

        public ObjectPoseRequest(Geometry.PointMsg[] position, Geometry.QuaternionMsg[] orientation)
        {
            this.position = position;
            this.orientation = orientation;
        }

        public static ObjectPoseRequest Deserialize(MessageDeserializer deserializer) => new ObjectPoseRequest(deserializer);

        private ObjectPoseRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.orientation, Geometry.QuaternionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.WriteLength(this.orientation);
            serializer.Write(this.orientation);
        }

        public override string ToString()
        {
            return "ObjectPoseRequest: " +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\norientation: " + System.String.Join(", ", orientation.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
