//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class PixelValueServiceRequest : Message
    {
        public const string k_RosMessageName = "ril_msg/PixelValueService";
        public override string RosMessageName => k_RosMessageName;

        public long pixel_state;

        public PixelValueServiceRequest()
        {
            this.pixel_state = 0;
        }

        public PixelValueServiceRequest(long pixel_state)
        {
            this.pixel_state = pixel_state;
        }

        public static PixelValueServiceRequest Deserialize(MessageDeserializer deserializer) => new PixelValueServiceRequest(deserializer);

        private PixelValueServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pixel_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pixel_state);
        }

        public override string ToString()
        {
            return "PixelValueServiceRequest: " +
            "\npixel_state: " + pixel_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
