//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class PixelValueResponse : Message
    {
        public const string k_RosMessageName = "ril_msg/PixelValue";
        public override string RosMessageName => k_RosMessageName;

        public float[] pixel_value;

        public PixelValueResponse()
        {
            this.pixel_value = new float[0];
        }

        public PixelValueResponse(float[] pixel_value)
        {
            this.pixel_value = pixel_value;
        }

        public static PixelValueResponse Deserialize(MessageDeserializer deserializer) => new PixelValueResponse(deserializer);

        private PixelValueResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pixel_value, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.pixel_value);
            serializer.Write(this.pixel_value);
        }

        public override string ToString()
        {
            return "PixelValueResponse: " +
            "\npixel_value: " + System.String.Join(", ", pixel_value.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
