//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class RandomSpawnRequest : Message
    {
        public const string k_RosMessageName = "ril_msg/RandomSpawn";
        public override string RosMessageName => k_RosMessageName;

        public string[] activated_object;
        public Geometry.PointMsg[] position;
        public Geometry.QuaternionMsg[] orientation;

        public RandomSpawnRequest()
        {
            this.activated_object = new string[0];
            this.position = new Geometry.PointMsg[0];
            this.orientation = new Geometry.QuaternionMsg[0];
        }

        public RandomSpawnRequest(string[] activated_object, Geometry.PointMsg[] position, Geometry.QuaternionMsg[] orientation)
        {
            this.activated_object = activated_object;
            this.position = position;
            this.orientation = orientation;
        }

        public static RandomSpawnRequest Deserialize(MessageDeserializer deserializer) => new RandomSpawnRequest(deserializer);

        private RandomSpawnRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activated_object, deserializer.ReadLength());
            deserializer.Read(out this.position, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.orientation, Geometry.QuaternionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.activated_object);
            serializer.Write(this.activated_object);
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.WriteLength(this.orientation);
            serializer.Write(this.orientation);
        }

        public override string ToString()
        {
            return "RandomSpawnRequest: " +
            "\nactivated_object: " + System.String.Join(", ", activated_object.ToList()) +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\norientation: " + System.String.Join(", ", orientation.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
