//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class RobotPlanRequest : Message
    {
        public const string k_RosMessageName = "ril_msg/RobotPlan";
        public override string RosMessageName => k_RosMessageName;

        public float[] joint_state;

        public RobotPlanRequest()
        {
            this.joint_state = new float[0];
        }

        public RobotPlanRequest(float[] joint_state)
        {
            this.joint_state = joint_state;
        }

        public static RobotPlanRequest Deserialize(MessageDeserializer deserializer) => new RobotPlanRequest(deserializer);

        private RobotPlanRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_state, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_state);
            serializer.Write(this.joint_state);
        }

        public override string ToString()
        {
            return "RobotPlanRequest: " +
            "\njoint_state: " + System.String.Join(", ", joint_state.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
