//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RilMsg
{
    [Serializable]
    public class RobotPlanResponse : Message
    {
        public const string k_RosMessageName = "ril_msg/RobotPlan";
        public override string RosMessageName => k_RosMessageName;

        public long execute_state;

        public RobotPlanResponse()
        {
            this.execute_state = 0;
        }

        public RobotPlanResponse(long execute_state)
        {
            this.execute_state = execute_state;
        }

        public static RobotPlanResponse Deserialize(MessageDeserializer deserializer) => new RobotPlanResponse(deserializer);

        private RobotPlanResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.execute_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.execute_state);
        }

        public override string ToString()
        {
            return "RobotPlanResponse: " +
            "\nexecute_state: " + execute_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
